### ISSUE TITLE
test failed

### ISSUE THREAD

**Issue by 0x10cxR1** [jvkersch/hsmmlearn#25] opened 2017-07-12 02:21 UTC
Hi,

after installing hsmmlearn, I ran "python3 -m unittest discover -v ."

I got: ImportError: No module named 'hsmmlearn.base".

Any idea why? Thanks.

**Comment by jvkersch** [comment] 2017-07-13 05:43
@Zhijing1128 I can't immediately figure out what would be the problem, but here are some questions to kick us off:

1. How did you install the package?

2. Can you check that you have the dependencies installed (e.g. through `pip freeze`)

3. In a python prompt, can you try `import hsmmlearn`, if that works, do `print(hsmmlearn.__file__)`. What does that give you?

**Comment by jvkersch** [comment] 2017-07-23 08:22
@Zhijing1128 Any word on this? I can't reproduce, so I'll close the issue, but feel free to reopen if you have things to add.

**Comment by nisheeths** [comment] 2021-08-20 00:17
I was having the same problem, and was able to debug it. The issue is that the installation instructions given [here](https://github.com/jvkersch/hsmmlearn) don't actually build the base.pyx to a module that python can use. Just running "python setup.py build_ext --inplace" after "python setup.py install" fixes the problem. Changing setup.py to ensure cython builds the module would obviate this step.

**Comment by jvkersch** [comment] 2021-08-21 12:32
@nisheeths Thanks for flagging this. I think I have  a fix for this in the making (#47 )

**Closed** 2021-08-21 12:33 UTC
